export const DAILY_WORDS_4 = ["LOVE", "CUTE", "HUGS", "KISS", "MOON", "STAR", "BABY", "SOUL", "MIND", "TIME", "LIFE", "CARE", "WARM", "FEEL", "HOPE", "TRUE", "PURE", "GLOW", "DEAR", "HOME", "FIRE", "WILD", "FREE", "BOLD", "EPIC", "HERO", "BOND", "MATE", "GIFT", "RICH", "CALM", "SOFT", "KIND", "FAIR", "DEEP", "VAST", "POEM", "SONG", "TALE", "PLAY"];

export const DAILY_WORDS_5 = ["SWEET", "HEART", "SMILE", "DREAM", "PEACE", "MAGIC", "TRUST", "BLISS", "ANGEL", "HONEY", "CHARM", "GRACE", "LIGHT", "STARS", "SPARK", "FLAME", "SHINE", "LAUGH", "TOUCH", "SENSE", "CRAZY", "SMART", "BRAVE", "PROUD", "LUCKY", "HAPPY", "FUNNY", "SILLY", "SWEAT", "TEARS", "TRUTH", "WORLD", "EARTH", "OCEAN", "RIVER", "BEAUT", "FAITH", "FOCUS", "POWER", "CATCH"];

export const DAILY_WORDS_6 = ["CARING", "LOVING", "GENTLE", "TENDER", "BEAUTY", "WONDER", "PASSION", "JOYFUL", "SPRING", "SUMMER", "AUTUMN", "WINTER", "FOREST", "NATURE", "COSMOS", "GALAXY", "SPIRIT", "KISSES", "HUGGED", "HEARTS", "ALWAYS", "FOREVER", "ETERNAL", "SACRED", "DIVINE", "PROMISE", "SECRET", "HONEST", "LOYALTY", "MEMORY", "FUTURE", "BRIGHT", "GOLDEN", "SILVER", "WARMTH", "DESIRE", "KINDLY", "GIFTED", "POETIC", "FEELING"];

export const DAILY_QUESTIONS = {
   random: [
     "What is my favorite color?", "What food do I hate the most?", "What is my dream vacation destination?", "What's my go-to fast food order?", "What song always gets me dancing?", "Who is my celebrity crush?", "What's my favorite movie genre?", "If I could only eat one meal for the rest of my life, what would it be?", "What's my favorite ice cream flavor?", "What's my preferred superpower?", "Are my eyes more brown, green, or blue?", "What was my favorite subject in high school?", "What is my biggest pet peeve?", "Do I prefer cats or dogs?", "Am I a morning person or a night owl?", "What's my favorite book of all time?", "Which fictional universe would I want to live in?", "If I won the lottery, what's the first thing I'd buy?", "What's my least favorite chore?", "Do I prefer coffee or tea?", "What's my favorite holiday?", "What's my typical coffee shop order?", "If I could time travel, would I go to the past or future?", "What's my favorite board game?", "What is my hidden talent?", "If I had to listen to one band forever, who would it be?", "What's my favorite season of the year?", "Do I prefer the beach or the mountains?", "What's the best gift I've ever received?", "What's my worst habit?", "What's my favorite TV show to binge-watch?", "If I could meet any historical figure, who would it be?", "What's my favorite type of cuisine?", "Do I like my chocolate dark, milk, or white?", "What is my favorite sport to play or watch?", "What is my go-to karaoke song?", "What is my biggest irrational fear?", "Which emoji do I use the most?", "If I were a vegetable, what would I be?", "What's my favorite quote?", "Do I prefer sweet or savory snacks?", "What is my favorite childhood cartoon?", "If I could instantly learn any language, what would it be?", "What's my favorite animal?", "Am I more of a spender or a saver?", "What is my favorite flower?", "What's my favorite way to spend a Sunday?", "What's my favorite app on my phone?", "Do I prefer driving or being a passenger?", "What's my favorite scent?"
   ],
   deep: [
     "What is my biggest fear?", "When did I know I loved you?", "What is my happiest childhood memory?", "What is a trait I admire most in you?", "What always cheers me up when I'm sad?", "What is my ultimate career goal?", "What is my definition of a successful life?", "What is a regret I still hold onto?", "What's my love language?", "How do I like to be comforted when I'm stressed?", "What's my biggest insecurity?", "What is my most cherished family tradition?", "What do I think happens after we die?", "What is the hardest lesson I've ever had to learn?", "What makes me feel the most alive?", "What is a dream I've never told anyone about?", "What do I consider my greatest achievement?", "What is my biggest relationship dealbreaker?", "How do I handle conflict or anger?", "What does 'home' mean to me?", "What is my deepest spiritual or philosophical belief?", "What memory makes me cry the easiest?", "What do I value most in a friendship?", "What is my most controversial opinion?", "What role do I think luck has played in my life?", "What is my biggest weakness?", "What's a risk I'm glad I took?", "What is a cause I care deeply about?", "What makes me feel most misunderstood?", "What's my most prized possession and why?", "How has my perspective on life changed in the last 5 years?", "What do I think is my best personality trait?", "What do I want people to say about me at my funeral?", "What's the hardest decision I've ever made?", "What's a childhood wound I'm still healing from?", "What's my favorite thing about myself?", "What do I think is the meaning of life?", "What's the most beautiful place I've ever been?", "What's my favorite memory of us together?", "What's something I've forgiven myself for?", "What's the best piece of advice I've ever received?", "What makes a relationship truly last?", "What is my relationship with my body like?", "How do I deal with failure?", "What do I need most when I'm exhausted?", "What do I think makes us so compatible?", "What's a moment that fundamentally changed me?", "What's the kindest thing someone has ever done for me?", "What is my favorite sound in the world?", "What does a perfect day look like to me?"
   ],
   funny: [
     "What is my most embarrassing habit?", "If I were an animal, what would I be?", "Who would play me in a movie?", "What is my weirdest quirk?", "What irrational thing makes me angry?", "What meme represents my life?", "What is the silliest thing I've ever cried over?", "If I was arrested with no explanation, what would my friends assume I did?", "What's my most ridiculous childhood belief?", "What's my worst cooking disaster?", "What's the most embarrassing phase I went through?", "What's a joke I always laugh at, no matter how bad?", "What is my clumsiest moment?", "If I were a ghost, how would I haunt people?", "What's the weirdest thing I do when I'm alone?", "What's the funniest miscommunication we've ever had?", "What's a song I secretly love but pretend to hate?", "What's my most unpopular food opinion?", "What's my funniest pet peeve?", "If I had a warning label, what would it say?", "What's my most dramatic reaction to a minor inconvenience?", "What's the weirdest dream I've ever had?", "What's the silliest thing I'm afraid of?", "What's the worst outfit I've ever worn?", "What's a movie trope that drives me crazy?", "If I was a wrestler, what would be my entrance theme?", "What's the weirdest combination of foods I enjoy?", "What's the most awkward thing I've done in public?", "What's a word I always pronounce incorrectly?", "What's the funniest typo I've ever sent?", "What's my worst pickup line?", "What's the strangest rabbit hole I've gone down on the internet?", "What's a TV character I irrationally hate?", "What's my funniest drunk or sleep-deprived story?", "What's the worst haircut I've ever had?", "What's a ridiculous argument we've had?", "What's the weirdest gift I've ever received?", "What's a talent I have that is completely useless?", "What's my funniest school memory?", "What's a phrase I use way too often?", "If I could only use three emojis forever, what would they be?", "What's the most embarrassing thing I've done for a crush?", "What's a conspiracy theory I actually kinda believe?", "What's the most ridiculous thing I've bought on impulse?", "What's my funniest encounter with a stranger?", "What's the worst movie I've ever seen?", "What's my funniest childhood nickname?", "If my life was a sitcom, what would be the title?", "What's the weirdest compliment I've ever received?", "What's my funniest moment from a family vacation?"
   ],
   spicy: [
     "What is my favorite physical feature of yours?", "Where is the craziest place we've done it?", "What is my secret fantasy?", "What outfit of yours do I love the most?", "What's my favorite way to be touched?", "What do I think is your sexiest quality?", "What was I thinking the first time we kissed?", "What is my favorite type of foreplay?", "What is a kink I'm curious about?", "What do I find most irresistible about you?", "What's my favorite time of day for intimacy?", "What's the hottest dream I've ever had about us?", "What's my favorite memory of us in the bedroom?", "What do I consider my best physical feature?", "What's a movie scene that always turns me on?", "What is my favorite position?", "What's the most adventurous thing I want to try?", "What's the sexiest piece of clothing I own?", "How do I like you to initiate intimacy?", "What's my favorite compliment to receive?", "What's the naughtiest thought I've had about you in public?", "What is a turn-off for me?", "What's my favorite place to be kissed?", "What's the longest we've ever gone without it?", "What is my opinion on public displays of affection?", "What's my favorite song to play in the background?", "What's a roleplay scenario I'd enjoy?", "What do I think about morning sex?", "What's the most spontaneous thing we've done sexually?", "What's a sexy secret I've kept from you?", "What's the sexiest text message I've ever sent?", "What's my favorite kind of lingerie?", "What's a sensual activity I want to do more often?", "What's the hottest thing you've ever said to me?", "What's my favorite memory of our honeymoon phase?", "What do I find most romantic?", "What's a boundary of mine in the bedroom?", "What's the sexiest thing you can wear to bed?", "What's my opinion on toys?", "What's the most intense orgasm I've ever had?", "What's a place I want to make love in the future?", "What's my favorite way to tease you?", "What's the sexiest surprise you've ever given me?", "What's a fantasy I have involving food or massage?", "What do I think is the most underrated intimate act?", "What's my favorite kind of kiss?", "What's the most romantic date we've ever had?", "What's a physical sensation I absolutely love?", "What's the sexiest thing about my own personality?", "What's my ultimate fantasy vacation for just the two of us?"
   ]
};
